remove manifest after script completes
...or if it fails

diff --git a/script/deploy b/script/deploy
--- a/script/deploy
+++ b/script/deploy
@@ -10,37 +10,48 @@
 #   https://github.com/dlapiduz/step-cloud-foundry-deploy/blob/master/run.sh
 
 set -e
+set -o pipefail
 set -x
 
 BLUE=$1
 GREEN="${BLUE}-B"
 
+
+finally ()
+{
+  # we don't want to keep the sensitive information around
+  rm $MANIFEST
+}
+
+on_fail () {
+  finally
+  echo "DEPLOY FAILED - you may need to check 'cf apps' and 'cf routes' and do manual cleanup"
+}
+
+
 # pull the up-to-date manifest from the BLUE (existing) application
 MANIFEST=$(mktemp -t "${BLUE}_manifest")
 cf create-app-manifest $BLUE -p $MANIFEST
 
-# try/catch
-# http://stackoverflow.com/a/22010339/358804
-{
-  DOMAIN=$(cat $MANIFEST | grep domain: | awk '{print $2}')
+# set up try/catch
+# http://stackoverflow.com/a/185900/358804
+trap on_fail ERR
 
-  # create the GREEN application
-  cf push $GREEN -f $MANIFEST -n $GREEN
-  # ensure it starts
-  curl --fail -I "https://${GREEN}.${DOMAIN}"
+DOMAIN=$(cat $MANIFEST | grep domain: | awk '{print $2}')
 
-  # add the "green" application to the "blue" load balancer
-  cf map-route $GREEN $DOMAIN -n $BLUE
+# create the GREEN application
+cf push $GREEN -f $MANIFEST -n $GREEN
+# ensure it starts
+curl --fail -I "https://${GREEN}.${DOMAIN}"
 
-  # cleanup
-  # TODO consider 'stop'-ing the BLUE instead of deleting it, so that depedencies are cached for next time
-  cf delete $BLUE -f
-  cf rename $GREEN $BLUE
-  cf delete-route $DOMAIN -n $GREEN -f
+# add the "green" application to the "blue" load balancer
+cf map-route $GREEN $DOMAIN -n $BLUE
 
-  echo "DONE"
-} || {
-  # we don't want to keep the sensitive information around
-  rm $MANIFEST
-  exit 1
-}
+# cleanup
+# TODO consider 'stop'-ing the BLUE instead of deleting it, so that depedencies are cached for next time
+cf delete $BLUE -f
+cf rename $GREEN $BLUE
+cf delete-route $DOMAIN -n $GREEN -f
+finally
+
+echo "DONE"
